### ISSUE TITLE
Missing Products In Meta

### ISSUE THREAD

**Issue by CalzaFino** [magento/meta-for-magento2#84] opened 2024-09-06 18:42 UTC
Magento 2.4.7-p2
PHP 8.3
meta-for-magento2 1.3.2

Module configured for Ads only

Expected result; All the products sync with Meta and "View all Synced products" in Magento populated with the products.

Actual result:

Not all of my products show up in Meta, also, some categories are missing.
The synced products list in Magento's FaceBook & Instagram dashboard is empty.

The file generated inside var/export (facebook_products.csv.gz) does not go over 2,000M in size. I tried changing the products and the file generated estops weirdly just before the 2,000M limit. In my case 1,994,247 and 1,989,894

Is this an intended limit for the file size? Can this be increased? I need about 50% more (3.000M)

**Comment by zlik** [comment] 2024-12-11 20:22
@CalzaFino, 

We were not able to reproduce. Can you please try increasing your `php.ini` parameters and see if it makes any difference?
```
memory_limit
post_max_size
upload_max_filesize
max_execution_time
max_input_time
```
Also, please update the extension to the latest version – we've made a bunch of improvements since `1.3.2`. I'll close this for now bug please feel free to reopen if it's still an issue for you. Thank you!

**Closed by zlik** 2024-12-11 20:22 UTC
