### ISSUE TITLE
Error while running setup:upgrade

### ISSUE THREAD

**Issue by JamelleG** [magento/meta-for-magento2#35] opened 2023-10-02 14:36 UTC
### Preconditions (*)

1. **Magento Version:** `2.4.5-p3`
2. **Meta for magento2 extension version:** `1.2.0`
3. **PHP Version:** `8.1`
4. Crons/consumers are running via DB, not rabbitmq

### Steps to reproduce (*)

1. Run `bin/magento setup:upgrade

### Expected result (*)

1.  `bin/magento setup: upgrade` runs as expected
2.  queues are set up in the database.

### Actual result (*)

We get the following error message `Error while checking if topic is synchronous` and the underlying error message we get is 
`Topic "persist.meta.log.immediately" is not configured.`

**Comment by zlik** [comment] 2023-10-03 22:41
@nrostrow-meta

**Comment by nrostrow-meta** [comment] 2023-10-05 18:04
Hi @JamelleG, looking into this. Can you check your env.php file to see if the following code block is present?

```
'queue' => [
    'consumers_wait_for_messages' => 1
]
```

It's okay if there are other items in the 'queue' field array but it seems like 'consumers_wait_for_messages' => 1 must be present. If that is missing can you try adding it and see if that resolves the issue?

I think that this may be the issue based on [https://magento.stackexchange.com/questions/284604/error-while-checking-if-topic-is-synchronous-on-setupupgrade](https://l.workplace.com/l.php?u=https%3A%2F%2Fmagento.stackexchange.com%2Fquestions%2F284604%2Ferror-while-checking-if-topic-is-synchronous-on-setupupgrade&h=AT0iAkNc7wbtHVu6PLv8UZwcJ6zYuDLhX5QluAw8EGuEjS3ZbdMVaX_gDofgjXxMl8zkwltkYbO8CPt6yK_lEM0HFc0a1MqcBcFAzg0s0WoKP5dXR3VPJerm4eT8JEZVLN8ymY8giRd4RUcsnx7LWgcGnEEGHa0UJMo3lg) and I verified that on all of my working instances that 'queue' field and item are present in the env.php files.

**Comment by nrostrow-meta** [comment] 2023-10-13 17:27
@JamelleG any update on if switching the value to 1 fixed the issue?

**Comment by cmorbitzer** [comment] 2024-05-14 22:23
@nrostrow-meta I get this message as well. None of the suggested solutions have helped. Have you made any progress on this?

**Comment by sol-loup** [comment] 2024-05-22 20:58
Hey @cmorbitzer, sorry to hear you're having issues. From our perspective, communication.xml and queue_publisher.xml are correctly configured to support this. Can you confirm you've cleared cache and run the setup:install commands?

Would you also mind providing the output of:

sudo bin/magento queue:consumers:list

**Comment by jigar48** [comment] 2024-07-28 11:14
If you running and using Redis cache then try to flush Redis cache and then run upgrade command, It help me to fix this issue.

command I used to flush redis cache `redis-cli flushall`

**Comment by zlik** [comment] 2024-12-01 18:20
Closing as the team is not able to reproduce.

**Closed** 2024-12-01 18:19 UTC
