### ISSUE TITLE
Image Upload is Getting Cropped in Magento Meta Extension

### ISSUE THREAD

**Issue by navsankar27** [magento/meta-for-magento2#68] opened 2024-05-21 04:04 UTC
Preconditions (*)
1. Magento version: 2.4.6 p5
2. Magento Meta extension version: 1.3.1
3. No relevant logs or error messages were observed.

### Steps to reproduce (*)
1. Create a Product in the Magento Admin Panel
2. Upload images to the Product
3. Observe that the uploaded image appears cropped in the Meta Commerce manager catalog

### Expected result (*)
The uploaded image should retain its original dimensions and should not be cropped.
NB: The setting for Image cropping in the Meta Commerce manager is enabled as "Show entire image in frame".

### Actual result (*)
The uploaded image is cropped, resulting in the loss of important parts of the image.

Additional Context:
This issue impacts the visual presentation of products, as important details in the images are lost due to cropping. The issue can not be seen if we upload the same image directly from the Meta Commerce manager. Are there any relevant configuration changes that might resolve this issue?

**Comment by sol-loup** [comment] 2024-05-21 19:22
Hey @navsankar27 , can you provide some screenshots of what you're seeing, or if possible, the id of your Meta Shop?

**Comment by pradeepkanaka** [comment] 2024-12-02 10:09
@navsankar27 If you could please send screenshots of the issue that you are experiencing would be helpful to fix the issue.

**Comment by zlik** [comment] 2024-12-03 23:14
Closing as we're unable to reproduce. In case this becomes an issue again, we'll reopen this. Thanks all.

**Closed by zlik** 2024-12-03 23:14 UTC
