### ISSUE TITLE
Unable to apply data patch when running setup:upgrade

### ISSUE THREAD

**Issue by bulldogm11** [magento/meta-for-magento2#46] opened 2023-11-28 16:13 UTC
### Preconditions (*)

1. Magento 2.4.6-p3
2. Meta Business 1.2.3 

### Steps to reproduce (*)

1. Installed Meta Business extension via composer
2. Ran setup:upgrade command

### Actual result (*)
Received error:

Unable to apply data patch Meta\BusinessExtension\Setup\Patch\Data\DeleteLegacyData for module Meta_BusinessExtension. Original exception message: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'titanfuel0727_mg1.eav_attribute' doesn't exist, query was: DELETE FROM `eav_attribute` WHERE (attribute_code = 'facebook_age_group')

**Comment by bsslv123** [comment] 2023-11-29 04:27
I got the same error with magento 2.4.6-p3 and the reason was that my magento setup with **prefix for tables** in database. You can temporarily create a patch for this. There's even more scenario we can get this error. _E.g: Table 'facebook_catalog_update' doesn't exist when trying to place order _

**Comment by likearocket** [comment] 2023-11-30 09:54
> @bulldogm11 I got the same error with magento 2.4.6-p3 and the reason was that my magento setup with **prefix for tables** in database. You can temporarily create a patch for this. There's even more scenario we can get this error. _E.g: Table 'facebook_catalog_update' doesn't exist when trying to place order_

Are you able to provide a copy of the patch please? As we're also having this issue as per my thread [https://github.com/magento/meta-for-magento2/issues/13](url)

**Comment by kestraly** [comment] 2024-02-07 08:57
Still problems with this and database prefixes

**Comment by angelo983** [comment] 2024-04-20 09:19
Duplicate of #13

**Comment by likearocket** [comment] 2024-05-10 14:16
This should be fixed in v1.3.1 - I've closed my issues as the latest version resolves issues with my tables having prefixes.

**Closed** 2024-10-01 05:27 UTC
